name: The Chef Jimmy
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#014188'
    - '#028ad2'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
